# Generated by Django 3.2.6 on 2021-09-11 19:25

import api_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='test',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='binance_public_api',
            field=api_auth.models.EncryptedApiField(blank=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='binance_secret_api',
            field=api_auth.models.EncryptedApiField(blank=True),
        ),
    ]
