# Generated by Django 3.2.6 on 2021-09-24 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('order_type', models.CharField(max_length=255)),
                ('time_in_force', models.CharField(max_length=255)),
                ('trigger', models.FloatField()),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('direction', models.CharField(max_length=255)),
                ('notify', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('action', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'alerts_model',
            },
        ),
    ]
